on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    name: E2E - Faraway
    runs-on: ubuntu-latest
    steps:
      - name: Chown workspace
        run: chown -R $(whoami) .

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6

      - name: Run E2E tests
        run: |
          docker-compose up --build --exit-code-from synpress
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          DOCKER_DEFAULT_PLATFORM: linux/amd64
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          NETWORK_NAME: ${{ vars.NETWORK_NAME }}
          RPC_URL: ${{ vars.RPC_URL }}
          CHAIN_ID: ${{ vars.CHAIN_ID }}
          BLOCK_EXPLORER: ${{ vars.BLOCK_EXPLORER }}
          SYMBOL: ${{ vars.SYMBOL }}
          DISPLAY_WIDTH: ${{ vars.DISPLAY_WIDTH }}
          DISPLAY_HEIGHT: ${{ vars.DISPLAY_HEIGHT }}
          FARAWAY_BACKEND_IMAGE_URL: ${{ vars.FARAWAY_BACKEND_IMAGE_URL }}
          FARAWAY_FRONTEND_IMAGE_URL: ${{ vars.FARAWAY_FRONTEND_IMAGE_URL}}
          DISPLAY_IMAGE_URL: ${{ vars.DISPLAY_IMAGE_URL }}

      - name: Archive E2E artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # pin@v2
        if: always()
        with:
          name: e2e-artifacts-faraway-res
          path: |
            docker/report/videos
            docker/report/screenshots
            docker/report/mocha-awesome
        continue-on-error: true